/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  DevOps: {
    Awesome: ["devops-resources"],
    Git: ["git/git-commands"],
    Linux: ["linux/linux-commands"]
    // Jenkins: ["jenkins"],
    // Gitlab: ["gitlab/gitlab-intro"],
  },
  Containers: {
    Docker: [ 
      "docker/container", 
      "docker/commands", 
      "docker/security"
    ],
    Compose: [
      "docker-compose",
      "compose/compose-up",
      "compose/compose-stop",
      "compose/compose-cheat-sheet",
    ],
  },
  K8S: {
    Kubernetes: [
      "kubernetes/architecture",
      "kubernetes/volumes",
      "kubernetes/cronjob",
      "kubernetes/secrets",
      "kubernetes/service-accounts",
      "kubernetes/kops",
      "kubernetes/k8s_cli",
      "kubernetes/minikube",
      // "kubernetes/helm-secrets"
    ],
  },
  profile: {
    Career: [
      "profile/pega",
      "profile/persistent",
      "profile/previous"
    ]
  },
  aws: {
    "Amazon Web Services": [
      // "aws/aws-ec2",
      // "aws/aws-iam",
      "aws/aws-aurora",
      "aws/aws-ssm",
      "aws/aws-s3"
    ],
  },
  iac: {
    Terraform: [
      "terraform",
      "terraform/providers",
      "terraform/syntax",
      "terraform/expressions",
      "terraform/terraform-cheat-sheet",
      "terraform/terraform-validate",
      // "terraform/terraform-plan",
      // "terraform/terraform-apply",
      "terraform/state",
      "terraform/terraform-best-practices"
    ],
  },
  "data science": {
    Pandas: [
      // "ml/ml", 
      "ml/pandas",
      "ml/data-explore" 
    ],
  },
  SRE: {
    "SLA/SLO/SLI": ["sre/sli", "sre/slo"],
  },
  Observability: {
    "Observability": ["sre/sli", "sre/slo"],
  },
  CAP: {
    Mongo: ["mongo/mongod_config", "mongo/replicaset", "mongo/postgres_queries"],
    Redis: ["redis/redis-basic"],
    Kafka: ["kafka/commands"]
  },
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
